### ISSUE TITLE
Month Change

### ISSUE THREAD

**Issue by vinayakvinayam** [peacechen/CalendarPicker#3]
i have a drop down of year and month. i am passing them to the Calender Picker. when i hit the submit button after selecting month and year am getting the correct response. but unfortunately the view is not changing to the selected month and year

![IMG20200111140950](https://user-images.githubusercontent.com/55052573/72201663-86c70380-347c-11ea-8cfd-844fb4abd0f4.jpg)

**Comment by peacechen** [comment]
We'll need your code snippet to debug this. You may not be passing the proper props.

**Comment by peacechen** [comment]
Please repost your question including code snippet on the main repo:
https://github.com/stephy/CalendarPicker/issues
